api/__init__.py
from api import *

controllers/__init__.py
from home import *

controllers/home.py
from flask import *
from extensions import db
import os

home = Blueprint('home', __name__, template_folder='templates')

@home.route('/', methods=['GET'])
def home_route():
	if 'username' not in session:
		return redirect(url_for("home.login_route"))

	else:
		return render_template("base.html")

@home.route('/login', methods=['GET'])
def login_route():
	return render_template("login.html")

@home.route('/create-account', methods=['GET'])
def create_route():
	return render_template("createAccount.html")

templates/base.html
<!doctype html>

<html lang="en">
<head>
	<link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
	
	<link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}">
</head>

<body>

	<div class="header">
		<div class="header-title">
			<h1>Halo Balance Manager</h1>
		</div>
	</div>

	<div class="log-status" id="banner">
	{% if 'username' not in session %}
		<p>Not logged in. <br> <a href="{{url_for('home.login_route')}}">Log in here</a></p>
	{% endif %}

	{% if 'username' in session %}
		<p>Logged in as {{session.username}}</p>
		<a href="{{url_for('api.logoutApi')}}"><button class="pure-button" id="logout">Sign Out</button></a>
	{% endif %}
	</div>


{% block content %}

	
	<div id="jav">
		<script type="text/javascript">

			$(document).ready(function() {


				//Gather balance for user's account 
				$.ajax({
					type: "GET",
					contentType: "application/json; charset=UTF-8",
					data: {},
					url: "{{url_for('api.homeApi')}}",
					success: function(data){

						var balance = data['balance'];

						if (balance > 0){
							$("#balance").html("<p style='color:green;'>$" + balance + "</p>");
						}
	
						else if (balance == 0){
							$("#balance").html("<p>$" + balance + "</p>");
						}

						else {
							$("#balance").html("<p style='color:red;'>$" + balance + "</p>");
						}

					},
					error: function(error){
						$("#balance").html("<p style='color:red;'> \*Could not retrieve account balance\* </p>");
						// console.log(error.responseText);
					}
				});//ajax call


				//Initiating the change in account balance
				$("#editFunds").click(function(){
					$(".changeAmount").toggle();
				});


				$('#deposit, #withdraw').click(function(event) {
					event.preventDefault();

					var deposit = false;
					var withdraw = false;
					var clicked = event.target.id;

					if (clicked == "deposit"){
						deposit = true;
						withdraw = false;
					}//if

					else if (clicked == "withdraw"){
						deposit = false;
						withdraw = true;
					}//if

					var amnt = document.getElementById('amount').value;

					//Validation checks
					var error = false;
					errors = []

					if (amnt == ''){
						error = true;
						errors.push('*Please specify how much you would like to deposit or withdraw*')
					}//blank entries error 


					if (error){
						htstr = "";
						var i = 0;
						for (i; i < errors.length; ++i){
							htstr += "<p style='color:red;'>" + errors[i] + "</p>";
						}//for 

						$("#errors").html(htstr);
					}//sending errors

					else {
						var userdata = {
							amount: amnt,
							dsit: deposit, 
							wdraw: withdraw
						}

						$.ajax({
							type: "SET",
							contentType: "application/json; charset=UTF-8",
							data: JSON.stringify(userdata),
							url: "{{url_for('api.homeApi')}}",
							success: function(data){
								// console.log(data)
								window.location.href = "{{url_for('home.home_route')}}";

							},
							error: function(error){
								// console.log(error.responseText);
								var eresponse = error.responseText;
								eresponse = eresponse.replace(/\\/g, "");
								$("#errors").html("<p style='color:red;'>" + eresponse + "</p>");

								//need to handle these error messages
							}


						});//ajax call
					}//else
				}); //submit function

			}); //document.ready

		</script>
	</div>

	<div class="main-container">

		<div id="balanceInfo">
			<p><u>Account Balance:</u></p>
			<div id="balance">
				
			</div>
		</div>
		
		<button class="pure-button" id="editFunds">Edit Balance</button><br>
		<div class="changeAmount" style="display: none">
			<form class="pure-form-aligned" id="logData2">

					<div class="pure-control-group" id="errors"></div>

					<div class="pure-control-group">
						<input id="amount" type="text" placeholder="Amount (in US Dollars)">
					</div>


					<div class="pure-controls" id="fundButtons">
						<button class="pure-button pure-button-primary" id="deposit" style="background: green;">Deposit</button>
						<button class="pure-button pure-button-primary" id="withdraw" style="background: red;">Withdraw</button>
					</div>

			</form>
		</div>


		<br><br>

		<div class="resultList">
			
		</div>
		
 
	</div>


{% endblock %}
</body>
</html>

templates/createAccount.html
{% extends "base.html" %}
{% block content %}
<div id="jav">
	<script type="text/javascript">

		$(document).ready(function() {
			$('#new-data').submit(function(event) {
				event.preventDefault();

				var fname = document.getElementById('firstName').value;
				var lname = document.getElementById('lastName').value;
				var uname = document.getElementById('username').value;
				var pass1 = document.getElementById('password1').value;
				var pass2 = document.getElementById('password2').value;


				//Validation checks
				error = false;
				errors = []

				if (fname == '' || lname == '' || uname == '' || pass1 == '' || pass2 == ''){
					error = true;
					errors.push('*All fields must be filled out to create an account*')
				}//blank entries error 


				if (pass1.length < 5){
					error = true;
					errors.push('*Passwords must have at least 5 characters*')
				}


				if (pass1 != pass2){
					error = true;
					errors.push('*The passwords do not match. Please re-enter them*')
				}//


				if (error){
					htstr = "";
					var i = 0;
					for (i; i < errors.length; ++i){
						htstr += "<p style='color:red;'>" + errors[i] + "</p>";
					}//for 

					$("#errors").html(htstr);
				}//sending errors

				else {
					var userdata = {
						username: uname,
						firstname: fname,
						lastname: lname,
						password: pass1
					}

					$.ajax({
						type: "POST",
						contentType: "application/json; charset=UTF-8",
						data: JSON.stringify(userdata),
						url: "{{url_for('api.createApi')}}",
						success: function(data){
							// console.log(data)
							window.location.href = "{{url_for('home.login_route')}}";
						},
						error: function(error){
							$("#errors").html("<p style='color:red;'>" + "\*" + error.responseText.slice(1, -2) + "\*" + "</p>");
							// console.log(error.responseText);
							//need to handle these error messages
						}


					});//ajax call
				}//else

			}); //submit function
		}); //document.ready
	
	</script>
</div>

<div class="create-account-form">
	<form class="pure-form-aligned" id="new-data">
		<fieldset>
			<legend>Please fill in the form to create an account</legend>

			<div class="pure-control-group" id="errors"></div>

			<div class="pure-control-group">
				<label for="firstName">First Name</label>
				<input id="firstName" type="text" placeholder="First Name">
			</div>

			<div class="pure-control-group">
				<label for="lastName">Last Name</label>
				<input id="lastName" type="text" placeholder="Last Name">
			</div>

			<div class="pure-control-group">
				<label for="username">Username</label>
				<input id="username" type="text" placeholder="Username">
			</div>

			<div class="pure-control-group">
				<label for="password1">Password</label>
				<input id="password1" type="password" placeholder="Password1">
			</div>

			<div class="pure-control-group">
				<label for="password2">Re-enter password</label>
				<input id="password2" type="password" placeholder="Password2">
			</div>

			<div class="pure-controls">
				<button type="submit" class="pure-button pure-button-primary">Create Account</button>
			</div>

		</fieldset>
	</form>
</div>


{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
<div id="jav">
	<script type="text/javascript">

		$(document).ready(function() {
			$('#logData').submit(function(event) {
				event.preventDefault();

				var uname = document.getElementById('name').value;
				var pass = document.getElementById('password').value;


				//Validation checks
				error = false;
				errors = []

				if (uname == '' || pass == ''){
					error = true;
					errors.push('*All fields must be filled out to log in*')
				}//blank entries error 


				if (error){
					htstr = "";
					var i = 0;
					for (i; i < errors.length; ++i){
						htstr += "<p style='color:red;'>" + errors[i] + "</p>";
					}//for 

					$("#errors").html(htstr);
				}//sending errors

				else {
					var userdata = {
						username: uname,
						password: pass
					}

					$.ajax({
						type: "POST",
						contentType: "application/json; charset=UTF-8",
						data: JSON.stringify(userdata),
						url: "{{url_for('api.loginApi')}}",
						success: function(data){
							// console.log(data)
							window.location.href = "{{url_for('home.home_route')}}";
						},
						error: function(error){
							// console.log(error.responseText);
							$("#errors").html("<p style='color:red;'>" + "\*" + error.responseText.slice(1, -2) + "\*" + "</p>");

							//need to handle these error messages
						}


					});//ajax call
				}//else

			}); //submit function
		}); //document.ready
	
	</script>
</div>


<div class="loginForm">
	<form class="pure-form-aligned" id="logData">
		<fieldset>
			<legend>Please sign in to the Halo Account Manager Website</legend>

			<div class="pure-control-group" id="errors"></div>

			<div class="pure-control-group">
				<label for="name">Username</label>
				<input id="name" type="text" placeholder="Username">
			</div>

			<div class="pure-control-group">
				<label for="password">Password</label>
				<input id="password" type="password" placeholder="Password">
			</div>

			<div class="pure-controls">
				<button type="submit" class="pure-button pure-button-primary">Sign in</button>
			</div>

		</fieldset>
	</form>
</div>

<div class="head-to-create">
	
	<p>Don't have an account? Make one <a href="{{url_for('home.create_route')}}"><button class="button-warning pure-button" style="background: #089BF7; padding:6.5px;">here.</button></a></p>

</div>


{% endblock %}